server.port = 5000
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost/botanice
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto = update
jwt.secret=5L/bIMDSR73WZm3keFtCmjSY0G4HrQrw1HAgdL+8rJU=
jwt.token.validity=3600
